{
 "title": "Ecommerce API Overview",
 "tags": [
  "ecommerce",
  "fastapi",
  "prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "RPS por Path",
   "type": "timeseries",
   "description": "Requests por segundo",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m])) by (path)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Latencia p95 por Path",
   "type": "timeseries",
   "description": "Latencia p95 por endpoint",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, path))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "HTTP Status (ultimos 5m)",
   "type": "piechart",
   "description": "Distribucion de codigos de respuesta",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total[5m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}